server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/banking_dbb
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show_sql: true



